/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 73078a6e99d44ace88096a4b13a0cb58)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ALLOWED_ORIGINS: "https://table.builtwai.com,https://table-sparks-game.pages.dev,https://*.table-sparks-game.pages.dev";
	ROOMS: DurableObjectNamespace<import("./worker/index").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
